### ISSUE TITLE
[FR] Allow control of multiple audio tracks

### ISSUE THREAD

**Issue by diingus** [bitwave-tv/bitwave#157]
This would be useful for streams which have music, so that you could turn it off / change the volume, provided the streamer has it set up in separate tracks.

**Comment by DispatchCommit** [comment]
Step 1: learn how to stream multiple audio tracks to the server... 🤔

**Comment by DispatchCommit** [comment]
A stream *must* be a single track audio source, so that instantly rules out being able to mute by audio track, but potentially using 3.1, or 5.1 (maybe even 7.1?) and the WebAudio API we could split apart a single track into multiple "streams", which could be independently volume controlled.

Splitting a multichannel audio source can be done with ChannelSplitterNode: 
https://developer.mozilla.org/en-US/docs/Web/API/ChannelSplitterNode

https://obsproject.com/wiki/Surround-Sound-Streaming-And-Recording

setup in OBS: 
![image](https://user-images.githubusercontent.com/45262335/113502140-2daf1980-94df-11eb-970c-e5524b7d78a6.png)

How do you get the audio from video.js to a WebAudio API for modifying it? no idea. 

probably need to start with accessing the audio track from video.js, see:  
https://docs.videojs.com/tutorial-audio-tracks.html

and then reading over this MDN article numerous times until you've learned enough to go understand what you need to google to learn how to actually implement splitting the track, adjusting it, and then finally downsampling back down to give the effect of modifying a multitrack source.

Yea, good luck.

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation
