### ISSUE TITLE
Provide documentation regarding stream encoder options

### ISSUE THREAD

**Issue by trapexit** [bitwave-tv/bitwave#24]
I'm using ffmpeg and I'm seeing the stream fall behind as if it's publishing faster than the framerate. These settings worked fine on other platforms. It's be nice to have encoder examples to help with such issues.

**Comment by DoxIsMightier** [comment]
`ffmpeg \
    -re \
    -stream_loop -1 \
    -i "$SOURCE" -deinterlace \
    -vf \
    "format=yuv444p, \
    drawbox=y=ih/PHI:color=black@0.4:width=iw:height=48:t=max, \
    drawtext=fontfile=/usr/share/fonts/truetype/open-sans/OpenSans-Regular.ttf:text='some overlay text for fun':fontcolor=white:fontsize=24:x=(w-tw)/2:y=(h/PHI)+th, \
    format=yuv420p" \
    -vcodec libx264 -pix_fmt yuv420p  -preset $QUAL -r $FPS -g $(($FPS * 2)) -b:v $VBR \
    -acodec aac -ar 44100 -threads 6 -qscale 3 -b:a 128K -bufsize 2048 \
    -f flv "$URL/$KEY"`

The key thing to note is the -re, which is the real time encoding flag that slows you down to ~.99x aka real time, otherwise you will have that problem you described.

**Comment by DispatchCommit** [comment]
ffmpeg is voodoo magic that I'm happy to help with, but most likely would not be able to create a well detailed guide that addresses the many potential edge cases with encoding issues.

Instead, the ingestion servers should be capable of handling all types of malformed incorrect, mistimed, broken input streams and still be able to provide some sort of consistent video output. In cases where it does not, the ingestion should be adjusted such that they are better fitted to more and more general cases uses over time, rather than attempting to solve 1 off bugs directly with stream sources.
